//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2007_lesson9_mon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public Nullable<System.DateTime> estimateShipDate { get; set; }
        public System.DateTime shipDate { get; set; }
        public int qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<int> productID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
