//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2007_lesson9_mon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retail
    {
        public Retail()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int retailID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string postalCode { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
